import type { FeedCard } from '@/types/content';

/**
 * SYNTHETIC DEMO CONTENT — not editorially reviewed.
 * Placeholder inventory so the feed is demoable before real Supabase content
 * and sourcing are in place. Replace via the CMS/admin workflow before launch;
 * do not ship these cards to production without source review.
 */
export const MOCK_FEED_CARDS: FeedCard[] = [
  {
    id: 'mock-1',
    type: 'fact',
    eyebrow: 'Companies',
    hook: 'Costco barely profits from what you buy.',
    body: 'Costco runs razor-thin margins on products and makes most of its profit from membership fees. That trade-off buys shopper loyalty and keeps prices aggressively low versus rivals.',
    difficulty: 1,
    estimatedSeconds: 18,
    entities: [{ type: 'company', slug: 'costco', name: 'Costco' }],
    sourceCount: 2,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-2',
    type: 'story',
    eyebrow: 'Company history · 1/3',
    hook: 'Apple was 90 days from bankruptcy in 1997.',
    body: "Apple had leaked cash for years and inventory was piling up unsold. Steve Jobs returned, killed most product lines, and took a $150M investment from Microsoft — a rival — just to stay alive.",
    difficulty: 1,
    estimatedSeconds: 25,
    entities: [
      { type: 'company', slug: 'apple', name: 'Apple' },
      { type: 'person', slug: 'steve-jobs', name: 'Steve Jobs' },
    ],
    sourceCount: 3,
    storySequence: 1,
    storyTotal: 3,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-3',
    type: 'person',
    eyebrow: 'People',
    hook: 'Warren Buffett learned investing from one professor.',
    body: "Buffett studied under Benjamin Graham at Columbia, absorbing 'value investing': buying businesses for meaningfully less than what they're worth. He later worked at Graham's firm before starting his own partnership at 25.",
    difficulty: 1,
    estimatedSeconds: 22,
    entities: [
      { type: 'person', slug: 'warren-buffett', name: 'Warren Buffett' },
      { type: 'person', slug: 'benjamin-graham', name: 'Benjamin Graham' },
    ],
    sourceCount: 2,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-4',
    type: 'quiz',
    eyebrow: 'Quick check',
    hook: 'When bond yields rise, bond prices...',
    body: 'Bond prices and yields move in opposite directions — this is one of the most tested relationships in fixed income.',
    difficulty: 2,
    estimatedSeconds: 15,
    entities: [{ type: 'topic', slug: 'bonds', name: 'Bonds' }],
    sourceCount: 1,
    isSaved: false,
    isFollowingPrimaryTopic: false,
    quiz: {
      questionId: 'mock-q-1',
      questionVersion: 1,
      prompt: 'When bond yields rise, what happens to existing bond prices?',
      type: 'multiple_choice',
      difficulty: 2,
      xpReward: 8,
      options: [
        { id: 'a', label: 'They fall' },
        { id: 'b', label: 'They rise' },
        { id: 'c', label: 'They stay the same' },
        { id: 'd', label: 'It depends only on the issuer' },
      ],
    },
  },
  {
    id: 'mock-5',
    type: 'company',
    eyebrow: 'Business model',
    hook: 'Visa never lends you a cent.',
    body: "Visa doesn't issue cards or extend credit — banks do that. Visa just moves the payment message between banks and takes a small cut of every swipe, which is why its margins are enormous.",
    difficulty: 1,
    estimatedSeconds: 20,
    entities: [{ type: 'company', slug: 'visa', name: 'Visa' }],
    sourceCount: 2,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-6',
    type: 'concept',
    eyebrow: 'Learn · Fixed income',
    hook: 'Duration measures a bond’s pain tolerance.',
    body: 'Duration estimates how much a bond’s price will move for a 1% change in interest rates. A higher duration means bigger price swings when rates move.',
    difficulty: 2,
    estimatedSeconds: 24,
    entities: [{ type: 'topic', slug: 'bonds', name: 'Bonds' }],
    sourceCount: 1,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-7',
    type: 'history',
    eyebrow: 'History · 45 seconds',
    hook: 'The dot-com bubble erased $5 trillion in months.',
    body: 'From 2000 to 2002, the Nasdaq fell nearly 78% as investors realized many internet companies had no real path to profit. Survivors like Amazon rebuilt slowly; hundreds of others vanished entirely.',
    difficulty: 2,
    estimatedSeconds: 28,
    entities: [{ type: 'topic', slug: 'market-crashes', name: 'Market Crashes' }],
    sourceCount: 3,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-8',
    type: 'comparison',
    eyebrow: 'Compare',
    hook: 'Visa vs. Mastercard: same job, same playbook.',
    body: 'Both companies run payment networks, not banks. Neither lends money or takes on credit risk. They compete almost entirely on network size, bank partnerships, and merchant acceptance.',
    difficulty: 1,
    estimatedSeconds: 20,
    entities: [
      { type: 'company', slug: 'visa', name: 'Visa' },
      { type: 'company', slug: 'mastercard', name: 'Mastercard' },
    ],
    sourceCount: 2,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-9',
    type: 'story',
    eyebrow: 'Company history · 2/3',
    hook: 'Jobs returned and cut Apple’s product line by 70%.',
    body: 'Facing 40 confusing product variants, Jobs reduced Apple to four core products on a simple grid: consumer vs. pro, desktop vs. portable. Focus, not new features, is what saved the company.',
    difficulty: 1,
    estimatedSeconds: 22,
    entities: [
      { type: 'company', slug: 'apple', name: 'Apple' },
      { type: 'person', slug: 'steve-jobs', name: 'Steve Jobs' },
    ],
    sourceCount: 2,
    storySequence: 2,
    storyTotal: 3,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-10',
    type: 'fact',
    eyebrow: 'Markets',
    hook: 'An ETF can hold thousands of stocks, and trade like one.',
    body: 'Exchange-traded funds bundle many securities into a single tradable share, giving instant diversification without buying every underlying stock individually.',
    difficulty: 1,
    estimatedSeconds: 16,
    entities: [{ type: 'topic', slug: 'etfs', name: 'ETFs' }],
    sourceCount: 1,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-11',
    type: 'quiz',
    eyebrow: 'Quick check',
    hook: 'True or false: ETFs can only track one industry.',
    body: 'ETFs range from broad market-wide funds to narrow single-industry funds — there is no single rule about scope.',
    difficulty: 1,
    estimatedSeconds: 12,
    entities: [{ type: 'topic', slug: 'etfs', name: 'ETFs' }],
    sourceCount: 1,
    isSaved: false,
    isFollowingPrimaryTopic: false,
    quiz: {
      questionId: 'mock-q-2',
      questionVersion: 1,
      prompt: 'True or false: an ETF can only track a single industry.',
      type: 'true_false',
      difficulty: 1,
      xpReward: 5,
      options: [
        { id: 'true', label: 'True' },
        { id: 'false', label: 'False' },
      ],
    },
  },
  {
    id: 'mock-12',
    type: 'person',
    eyebrow: 'People',
    hook: 'Jensen Huang kept NVIDIA alive by betting on gamers.',
    body: 'Before AI, NVIDIA survived on graphics chips for PC gaming through several near-death moments, including a 1990s chip that nearly bankrupted the company before it shipped.',
    difficulty: 2,
    estimatedSeconds: 24,
    entities: [
      { type: 'person', slug: 'jensen-huang', name: 'Jensen Huang' },
      { type: 'company', slug: 'nvidia', name: 'NVIDIA' },
    ],
    sourceCount: 2,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-13',
    type: 'concept',
    eyebrow: 'Learn · Personal finance',
    hook: 'Your budget is a forecast, not a punishment.',
    body: 'A useful budget gives every dollar a job before the month starts. Begin with take-home pay, subtract fixed needs, then assign what remains to flexible spending, savings, and debt. The point is visibility, not perfection.',
    difficulty: 1,
    estimatedSeconds: 28,
    entities: [{ type: 'topic', slug: 'budgeting', name: 'Budgeting' }],
    sourceCount: 2,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-14',
    type: 'concept',
    eyebrow: 'Learn · Cash flow',
    hook: 'Profit and cash are not the same thing.',
    body: 'A company can report a profit while cash is tied up in unpaid invoices or inventory. The cash flow statement follows money moving in and out, which helps explain whether a business can fund operations, repay debt, and invest for the future.',
    difficulty: 2,
    estimatedSeconds: 31,
    entities: [{ type: 'topic', slug: 'cash-flow', name: 'Cash Flow' }],
    sourceCount: 2,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-15',
    type: 'fact',
    eyebrow: 'Markets · Inflation',
    hook: 'Inflation is a change in purchasing power.',
    body: 'When prices rise broadly, each dollar buys less than before. A 3% annual inflation rate does not mean every item rises by 3%, but it does make the real return on your savings and investments more important to track.',
    difficulty: 1,
    estimatedSeconds: 25,
    entities: [{ type: 'topic', slug: 'inflation', name: 'Inflation' }],
    sourceCount: 2,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-16',
    type: 'concept',
    eyebrow: 'Learn · Credit',
    hook: 'A credit score is a risk signal, not a report card.',
    body: 'Lenders use credit history to estimate how reliably someone has repaid borrowed money. Payment history, balances relative to limits, account age, and recent applications can all matter. A score is one input in a decision, not a measure of your worth.',
    difficulty: 1,
    estimatedSeconds: 30,
    entities: [{ type: 'topic', slug: 'credit', name: 'Credit' }],
    sourceCount: 2,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-17',
    type: 'comparison',
    eyebrow: 'Investing · Risk',
    hook: 'Diversification cannot remove risk. It can narrow the surprises.',
    body: 'Owning different assets, industries, and regions can reduce the damage caused by one weak investment. It does not guarantee a profit, and it cannot protect a portfolio from a broad market decline, but it makes one company less able to decide your outcome.',
    difficulty: 2,
    estimatedSeconds: 29,
    entities: [{ type: 'topic', slug: 'diversification', name: 'Diversification' }],
    sourceCount: 2,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-18',
    type: 'concept',
    eyebrow: 'Learn · Valuation',
    hook: 'A low share price does not automatically mean a cheap company.',
    body: 'Price is the number attached to one share. Value depends on the whole business: its earnings, cash flow, debt, growth prospects, and the price paid for those qualities. Investors often use ratios to compare price with a company’s underlying economics.',
    difficulty: 2,
    estimatedSeconds: 30,
    entities: [{ type: 'topic', slug: 'valuation', name: 'Valuation' }],
    sourceCount: 2,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-19',
    type: 'history',
    eyebrow: 'History · Housing',
    hook: 'The 2008 crisis began with housing, then moved through the financial system.',
    body: 'As US home prices fell, rising defaults damaged mortgage-backed securities held across the financial system. The lesson is not simply that housing is risky: leverage, opaque products, and interconnected institutions can turn a local problem into a systemic one.',
    difficulty: 2,
    estimatedSeconds: 32,
    entities: [{ type: 'topic', slug: 'financial-crises', name: 'Financial Crises' }],
    sourceCount: 3,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-20',
    type: 'quiz',
    eyebrow: 'Quick check · Investing',
    hook: 'Which habit usually reduces concentration risk?',
    body: 'Spreading exposure across different investments can lower the impact of one company or sector performing badly.',
    difficulty: 1,
    estimatedSeconds: 18,
    entities: [{ type: 'topic', slug: 'diversification', name: 'Diversification' }],
    sourceCount: 1,
    isSaved: false,
    isFollowingPrimaryTopic: false,
    quiz: {
      questionId: 'mock-q-3',
      questionVersion: 1,
      prompt: 'Which action most directly reduces concentration risk?',
      type: 'multiple_choice',
      difficulty: 1,
      xpReward: 6,
      options: [
        { id: 'a', label: 'Put all your money in one familiar company' },
        { id: 'b', label: 'Spread exposure across different assets' },
        { id: 'c', label: 'Only buy investments with the lowest share price' },
        { id: 'd', label: 'Check your portfolio every five minutes' },
      ],
    },
  },
];

/**
 * Demo-only answer key. In production, correctness is decided exclusively by
 * the server (submit_quiz_answer RPC) — the correct option id must never
 * ship to the client ahead of submission.
 */
export const MOCK_QUIZ_ANSWERS: Record<string, { correctOptionId: string; explanation: string }> = {
  'mock-q-1': {
    correctOptionId: 'a',
    explanation:
      'Bond prices and yields move inversely. When new bonds pay higher yields, existing lower-yield bonds become less attractive, so their price falls.',
  },
  'mock-q-2': {
    correctOptionId: 'false',
    explanation:
      'ETFs span everything from total-market funds to single-industry or even single-theme funds — scope varies widely by fund.',
  },
  'mock-q-3': {
    correctOptionId: 'b',
    explanation: 'Diversification spreads exposure across investments so one company, sector, or asset has less power to determine the whole result.',
  },
};

