import type { FeedCard } from '@/types/content';

/**
 * SYNTHETIC DEMO CONTENT — not editorially reviewed.
 * Placeholder inventory so the feed is demoable before real Supabase content
 * and sourcing are in place. Replace via the CMS/admin workflow before launch;
 * do not ship these cards to production without source review.
 */
export const MOCK_FEED_CARDS: FeedCard[] = [
  {
    id: 'mock-1',
    type: 'fact',
    eyebrow: 'Companies',
    hook: 'Costco barely profits from what you buy.',
    body: 'Costco runs razor-thin margins on products and makes most of its profit from membership fees. That trade-off buys shopper loyalty and keeps prices aggressively low versus rivals.',
    difficulty: 1,
    estimatedSeconds: 18,
    entities: [{ type: 'company', slug: 'costco', name: 'Costco' }],
    sourceCount: 2,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-2',
    type: 'story',
    eyebrow: 'Company history · 1/3',
    hook: 'Apple was 90 days from bankruptcy in 1997.',
    body: "Apple had leaked cash for years and inventory was piling up unsold. Steve Jobs returned, killed most product lines, and took a $150M investment from Microsoft — a rival — just to stay alive.",
    difficulty: 1,
    estimatedSeconds: 25,
    entities: [
      { type: 'company', slug: 'apple', name: 'Apple' },
      { type: 'person', slug: 'steve-jobs', name: 'Steve Jobs' },
    ],
    sourceCount: 3,
    storySequence: 1,
    storyTotal: 3,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-3',
    type: 'person',
    eyebrow: 'People',
    hook: 'Warren Buffett learned investing from one professor.',
    body: "Buffett studied under Benjamin Graham at Columbia, absorbing 'value investing': buying businesses for meaningfully less than what they're worth. He later worked at Graham's firm before starting his own partnership at 25.",
    difficulty: 1,
    estimatedSeconds: 22,
    entities: [
      { type: 'person', slug: 'warren-buffett', name: 'Warren Buffett' },
      { type: 'person', slug: 'benjamin-graham', name: 'Benjamin Graham' },
    ],
    sourceCount: 2,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-4',
    type: 'quiz',
    eyebrow: 'Quick check',
    hook: 'When bond yields rise, bond prices...',
    body: 'Bond prices and yields move in opposite directions — this is one of the most tested relationships in fixed income.',
    difficulty: 2,
    estimatedSeconds: 15,
    entities: [{ type: 'topic', slug: 'bonds', name: 'Bonds' }],
    sourceCount: 1,
    isSaved: false,
    isFollowingPrimaryTopic: false,
    quiz: {
      questionId: 'mock-q-1',
      questionVersion: 1,
      prompt: 'When bond yields rise, what happens to existing bond prices?',
      type: 'multiple_choice',
      difficulty: 2,
      xpReward: 8,
      options: [
        { id: 'a', label: 'They fall' },
        { id: 'b', label: 'They rise' },
        { id: 'c', label: 'They stay the same' },
        { id: 'd', label: 'It depends only on the issuer' },
      ],
    },
  },
  {
    id: 'mock-5',
    type: 'company',
    eyebrow: 'Business model',
    hook: 'Visa never lends you a cent.',
    body: "Visa doesn't issue cards or extend credit — banks do that. Visa just moves the payment message between banks and takes a small cut of every swipe, which is why its margins are enormous.",
    difficulty: 1,
    estimatedSeconds: 20,
    entities: [{ type: 'company', slug: 'visa', name: 'Visa' }],
    sourceCount: 2,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-6',
    type: 'concept',
    eyebrow: 'Learn · Fixed income',
    hook: 'Duration measures a bond’s pain tolerance.',
    body: 'Duration estimates how much a bond’s price will move for a 1% change in interest rates. A higher duration means bigger price swings when rates move.',
    difficulty: 2,
    estimatedSeconds: 24,
    entities: [{ type: 'topic', slug: 'bonds', name: 'Bonds' }],
    sourceCount: 1,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-7',
    type: 'history',
    eyebrow: 'History · 45 seconds',
    hook: 'The dot-com bubble erased $5 trillion in months.',
    body: 'From 2000 to 2002, the Nasdaq fell nearly 78% as investors realized many internet companies had no real path to profit. Survivors like Amazon rebuilt slowly; hundreds of others vanished entirely.',
    difficulty: 2,
    estimatedSeconds: 28,
    entities: [{ type: 'topic', slug: 'market-crashes', name: 'Market Crashes' }],
    sourceCount: 3,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-8',
    type: 'comparison',
    eyebrow: 'Compare',
    hook: 'Visa vs. Mastercard: same job, same playbook.',
    body: 'Both companies run payment networks, not banks. Neither lends money or takes on credit risk. They compete almost entirely on network size, bank partnerships, and merchant acceptance.',
    difficulty: 1,
    estimatedSeconds: 20,
    entities: [
      { type: 'company', slug: 'visa', name: 'Visa' },
      { type: 'company', slug: 'mastercard', name: 'Mastercard' },
    ],
    sourceCount: 2,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-9',
    type: 'story',
    eyebrow: 'Company history · 2/3',
    hook: 'Jobs returned and cut Apple’s product line by 70%.',
    body: 'Facing 40 confusing product variants, Jobs reduced Apple to four core products on a simple grid: consumer vs. pro, desktop vs. portable. Focus, not new features, is what saved the company.',
    difficulty: 1,
    estimatedSeconds: 22,
    entities: [
      { type: 'company', slug: 'apple', name: 'Apple' },
      { type: 'person', slug: 'steve-jobs', name: 'Steve Jobs' },
    ],
    sourceCount: 2,
    storySequence: 2,
    storyTotal: 3,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-10',
    type: 'fact',
    eyebrow: 'Markets',
    hook: 'An ETF can hold thousands of stocks, and trade like one.',
    body: 'Exchange-traded funds bundle many securities into a single tradable share, giving instant diversification without buying every underlying stock individually.',
    difficulty: 1,
    estimatedSeconds: 16,
    entities: [{ type: 'topic', slug: 'etfs', name: 'ETFs' }],
    sourceCount: 1,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
  {
    id: 'mock-11',
    type: 'quiz',
    eyebrow: 'Quick check',
    hook: 'True or false: ETFs can only track one industry.',
    body: 'ETFs range from broad market-wide funds to narrow single-industry funds — there is no single rule about scope.',
    difficulty: 1,
    estimatedSeconds: 12,
    entities: [{ type: 'topic', slug: 'etfs', name: 'ETFs' }],
    sourceCount: 1,
    isSaved: false,
    isFollowingPrimaryTopic: false,
    quiz: {
      questionId: 'mock-q-2',
      questionVersion: 1,
      prompt: 'True or false: an ETF can only track a single industry.',
      type: 'true_false',
      difficulty: 1,
      xpReward: 5,
      options: [
        { id: 'true', label: 'True' },
        { id: 'false', label: 'False' },
      ],
    },
  },
  {
    id: 'mock-12',
    type: 'person',
    eyebrow: 'People',
    hook: 'Jensen Huang kept NVIDIA alive by betting on gamers.',
    body: 'Before AI, NVIDIA survived on graphics chips for PC gaming through several near-death moments, including a 1990s chip that nearly bankrupted the company before it shipped.',
    difficulty: 2,
    estimatedSeconds: 24,
    entities: [
      { type: 'person', slug: 'jensen-huang', name: 'Jensen Huang' },
      { type: 'company', slug: 'nvidia', name: 'NVIDIA' },
    ],
    sourceCount: 2,
    isSaved: false,
    isFollowingPrimaryTopic: false,
  },
];

/**
 * Demo-only answer key. In production, correctness is decided exclusively by
 * the server (submit_quiz_answer RPC) — the correct option id must never
 * ship to the client ahead of submission.
 */
export const MOCK_QUIZ_ANSWERS: Record<string, { correctOptionId: string; explanation: string }> = {
  'mock-q-1': {
    correctOptionId: 'a',
    explanation:
      'Bond prices and yields move inversely. When new bonds pay higher yields, existing lower-yield bonds become less attractive, so their price falls.',
  },
  'mock-q-2': {
    correctOptionId: 'false',
    explanation:
      'ETFs span everything from total-market funds to single-industry or even single-theme funds — scope varies widely by fund.',
  },
};

