/** SYNTHETIC DEMO CONTENT — placeholder entity profiles, not editorially reviewed. */
import type { CardRarity } from '@/types/content';

export type PersonProfile = {
  slug: string;
  name: string;
  descriptor: string;
  roles: string[];
  timeline: { year: string; text: string }[];
  rarity: CardRarity;
  /** Present on the global-roster batch (docs/global-roster-research.json) — absent on the original hand-written entries. */
  country?: string;
  sourceConfidence?: 'verified' | 'uncertain';
};

export type CompanyProfile = {
  slug: string;
  name: string;
  ticker?: string;
  industry: string;
  foundingYear: number;
  headquarters: string;
  description: string;
  howItMakesMoney: string;
  timeline: { year: string; text: string }[];
};

export type TopicProfile = {
  slug: string;
  name: string;
  category: string;
  description: string;
};

export const MOCK_PEOPLE: Record<string, PersonProfile> = {
  'steve-jobs': {
    slug: 'steve-jobs',
    name: 'Steve Jobs',
    descriptor: 'Co-founder and former CEO of Apple',
    roles: ['founder', 'CEO'],
    timeline: [
      { year: '1976', text: 'Co-founded Apple in a garage.' },
      { year: '1985', text: 'Forced out of Apple after a boardroom struggle.' },
      { year: '1997', text: 'Returned as Apple neared bankruptcy.' },
      { year: '2001', text: 'Launched the iPod, reshaping Apple’s business.' },
    ],
    rarity: 'legendary',
  },
  'warren-buffett': {
    slug: 'warren-buffett',
    name: 'Warren Buffett',
    descriptor: 'Chairman and CEO of Berkshire Hathaway',
    roles: ['investor', 'CEO'],
    timeline: [
      { year: '1951', text: 'Studied value investing under Benjamin Graham.' },
      { year: '1965', text: 'Took control of Berkshire Hathaway.' },
      { year: '2008', text: 'Invested billions during the financial crisis.' },
    ],
    rarity: 'legendary',
  },
  'benjamin-graham': {
    slug: 'benjamin-graham',
    name: 'Benjamin Graham',
    descriptor: 'Economist known as the father of value investing',
    roles: ['economist', 'investor'],
    timeline: [{ year: '1949', text: 'Published "The Intelligent Investor."' }],
    rarity: 'rare',
  },
  'jensen-huang': {
    slug: 'jensen-huang',
    name: 'Jensen Huang',
    descriptor: 'Co-founder and CEO of NVIDIA',
    roles: ['founder', 'CEO'],
    timeline: [
      { year: '1993', text: 'Co-founded NVIDIA.' },
      { year: '2006', text: 'Launched CUDA, betting on general-purpose GPU computing.' },
    ],
    rarity: 'epic',
  },
  'satya-nadella': {
    slug: 'satya-nadella',
    name: 'Satya Nadella',
    descriptor: 'Chairman and CEO of Microsoft',
    roles: ['CEO'],
    timeline: [{ year: '2014', text: 'Became CEO, pivoting Microsoft toward cloud computing.' }],
    rarity: 'common',
  },
  'jamie-dimon': {
    slug: 'jamie-dimon',
    name: 'Jamie Dimon',
    descriptor: 'Chairman and CEO of JPMorgan Chase',
    roles: ['CEO'],
    timeline: [{ year: '2005', text: 'Became CEO of JPMorgan Chase.' }],
    rarity: 'common',
  },
  // --- Global roster (docs/global-roster-research.json) — draft, not editorially reviewed ---
  'gina-rinehart': {
    slug: 'gina-rinehart',
    name: 'Gina Rinehart',
    descriptor: 'CEO — Hancock Prospecting',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Gina Rinehart is executive chairman of Hancock Prospecting, a privately owned iron ore mining company founded by her father, and is consistently ranked as Australia\'s richest person by Forbes.' }],
    rarity: 'epic',
    country: 'Australia',
    sourceConfidence: 'verified',
  },
  'graeme-hart': {
    slug: 'graeme-hart',
    name: 'Graeme Hart',
    descriptor: 'Investor — Rank Group',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Graeme Hart owns Rank Group, a private investment company known for leveraged buyouts in the packaging industry, and is New Zealand\'s wealthiest individual per Forbes.' }],
    rarity: 'rare',
    country: 'New Zealand',
    sourceConfidence: 'verified',
  },
  'marcos-galperin': {
    slug: 'marcos-galperin',
    name: 'Marcos Galperin',
    descriptor: 'Founder — MercadoLibre',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Marcos Galperin co-founded MercadoLibre in 1999 and led it as CEO for over two decades, and Forbes ranks him as Argentina\'s richest person.' }],
    rarity: 'epic',
    country: 'Argentina',
    sourceConfidence: 'verified',
  },
  'marcelo-claure': {
    slug: 'marcelo-claure',
    name: 'Marcelo Claure',
    descriptor: 'Founder — Bicycle Capital',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Marcelo Claure, a Bolivian-American entrepreneur and former Sprint CEO, founded Bicycle Capital, a growth-equity fund focused on Latin American startups.' }],
    rarity: 'rare',
    country: 'Bolivia',
    sourceConfidence: 'verified',
  },
  'jorge-paulo-lemann': {
    slug: 'jorge-paulo-lemann',
    name: 'Jorge Paulo Lemann',
    descriptor: 'Founder — 3G Capital',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Jorge Paulo Lemann co-founded investment firm 3G Capital, which built stakes in Anheuser-Busch InBev, Kraft Heinz, and Burger King.' }],
    rarity: 'epic',
    country: 'Brazil',
    sourceConfidence: 'verified',
  },
  'iris-fontbona': {
    slug: 'iris-fontbona',
    name: 'Iris Fontbona',
    descriptor: 'Investor — Antofagasta plc / Grupo Luksic',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Iris Fontbona controls the Luksic Group, including majority ownership of copper miner Antofagasta plc, and Forbes ranks her as Chile\'s richest person.' }],
    rarity: 'rare',
    country: 'Chile',
    sourceConfidence: 'verified',
  },
  'luis-carlos-sarmiento': {
    slug: 'luis-carlos-sarmiento',
    name: 'Luis Carlos Sarmiento',
    descriptor: 'Founder — Grupo Aval',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Luis Carlos Sarmiento founded and chairs Grupo Aval, a banking conglomerate controlling several of Colombia\'s largest banks.' }],
    rarity: 'rare',
    country: 'Colombia',
    sourceConfidence: 'verified',
  },
  'isabel-noboa': {
    slug: 'isabel-noboa',
    name: 'Isabel Noboa',
    descriptor: 'Founder — Nobis Consortium',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Isabel Noboa founded and leads the Nobis Consortium, one of Ecuador\'s largest business groups spanning real estate, bottling, and sugar production.' }],
    rarity: 'rare',
    country: 'Ecuador',
    sourceConfidence: 'verified',
  },
  'yesu-persaud': {
    slug: 'yesu-persaud',
    name: 'Yesu Persaud',
    descriptor: 'Founder — Demerara Distillers Limited',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Dr. Yesu Persaud led the merger that created Demerara Distillers Limited, building the El Dorado rum brand into an internationally distributed spirit.' }],
    rarity: 'rare',
    country: 'Guyana',
    sourceConfidence: 'verified',
  },
  'horacio-cartes': {
    slug: 'horacio-cartes',
    name: 'Horacio Cartes',
    descriptor: 'Founder — Tabacalera del Este (Grupo Cartes)',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Horacio Cartes built a business conglomerate in Paraguay spanning tobacco manufacturing, beverages, and banking before serving as President of Paraguay.' }],
    rarity: 'rare',
    country: 'Paraguay',
    sourceConfidence: 'verified',
  },
  'carlos-rodriguez-pastor': {
    slug: 'carlos-rodriguez-pastor',
    name: 'Carlos Rodriguez-Pastor',
    descriptor: 'CEO — Intercorp',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Carlos Rodriguez-Pastor is chairman and CEO of Intercorp, a Peruvian conglomerate including Interbank and Plaza Vea supermarkets.' }],
    rarity: 'rare',
    country: 'Peru',
    sourceConfidence: 'verified',
  },
  'dilip-sardjoe': {
    slug: 'dilip-sardjoe',
    name: 'Dilip Sardjoe',
    descriptor: 'Founder — Rudisa Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Dilip Sardjoe founded Rudisa International, building a multi-company conglomerate known for soft drink production and distribution in Suriname.' }],
    rarity: 'rare',
    country: 'Suriname',
    sourceConfidence: 'verified',
  },
  'sergio-fogel': {
    slug: 'sergio-fogel',
    name: 'Sergio Fogel',
    descriptor: 'Founder — dLocal',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Sergio Fogel co-founded Montevideo-based fintech payments company dLocal, becoming recognized as Uruguay\'s first billionaire after its 2021 Nasdaq listing.' }],
    rarity: 'rare',
    country: 'Uruguay',
    sourceConfidence: 'verified',
  },
  'lorenzo-mendoza': {
    slug: 'lorenzo-mendoza',
    name: 'Lorenzo Mendoza',
    descriptor: 'CEO — Empresas Polar',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Lorenzo Mendoza is CEO of Empresas Polar, Venezuela\'s largest privately held company, representing the third generation of his family to lead it.' }],
    rarity: 'rare',
    country: 'Venezuela',
    sourceConfidence: 'verified',
  },
  'ruben-vardanyan': {
    slug: 'ruben-vardanyan',
    name: 'Ruben Vardanyan',
    descriptor: 'Founder — Troika Dialog',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Ruben Vardanyan co-founded the Troika Dialog investment bank in 1991 and served as its CEO.' }],
    rarity: 'rare',
    country: 'Armenia',
    sourceConfidence: 'verified',
  },
  'vagit-alekperov': {
    slug: 'vagit-alekperov',
    name: 'Vagit Alekperov',
    descriptor: 'CEO — LUKOIL',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Vagit Alekperov, born in Baku, Azerbaijan, became president and chairman of the Russian oil company LUKOIL after its formation in 1993.' }],
    rarity: 'common',
    country: 'Azerbaijan',
    sourceConfidence: 'uncertain',
  },
  'nemir-kirdar': {
    slug: 'nemir-kirdar',
    name: 'Nemir Kirdar',
    descriptor: 'Founder — Investcorp',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Nemir Kirdar founded Investcorp, an alternative investment firm headquartered in Manama, Bahrain, in 1982.' }],
    rarity: 'rare',
    country: 'Bahrain',
    sourceConfidence: 'verified',
  },
  'muhammad-yunus': {
    slug: 'muhammad-yunus',
    name: 'Muhammad Yunus',
    descriptor: 'Founder — Grameen Bank',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Muhammad Yunus founded Grameen Bank in Bangladesh in 1983 to pioneer microcredit lending and won the Nobel Peace Prize in 2006.' }],
    rarity: 'rare',
    country: 'Bangladesh',
    sourceConfidence: 'verified',
  },
  'kith-meng': {
    slug: 'kith-meng',
    name: 'Kith Meng',
    descriptor: 'Founder — Royal Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Kith Meng founded Cambodia\'s Royal Group in 1990, a conglomerate spanning telecommunications and banking.' }],
    rarity: 'rare',
    country: 'Cambodia',
    sourceConfidence: 'verified',
  },
  'jack-ma': {
    slug: 'jack-ma',
    name: 'Jack Ma',
    descriptor: 'Founder — Alibaba Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Jack Ma co-founded Alibaba Group in 1999 and built it into one of the world\'s largest e-commerce companies.' }],
    rarity: 'legendary',
    country: 'China',
    sourceConfidence: 'verified',
  },
  'stelios-haji-ioannou': {
    slug: 'stelios-haji-ioannou',
    name: 'Stelios Haji-Ioannou',
    descriptor: 'Founder — easyGroup / easyJet',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Stelios Haji-Ioannou founded the airline easyJet in 1995 and chairs easyGroup, the holding company for his \'Easy\'-branded ventures.' }],
    rarity: 'rare',
    country: 'Cyprus',
    sourceConfidence: 'verified',
  },
  'bidzina-ivanishvili': {
    slug: 'bidzina-ivanishvili',
    name: 'Bidzina Ivanishvili',
    descriptor: 'Founder — Rossiysky Kredit / Cartu Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Bidzina Ivanishvili built his fortune in banking and metals in Russia, including co-founding Rossiysky Kredit bank, before returning to Georgia.' }],
    rarity: 'rare',
    country: 'Georgia',
    sourceConfidence: 'verified',
  },
  'mukesh-ambani': {
    slug: 'mukesh-ambani',
    name: 'Mukesh Ambani',
    descriptor: 'CEO — Reliance Industries',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Mukesh Ambani is chairman and managing director of Reliance Industries and is ranked by Forbes as Asia\'s wealthiest person.' }],
    rarity: 'legendary',
    country: 'India',
    sourceConfidence: 'verified',
  },
  'prajogo-pangestu': {
    slug: 'prajogo-pangestu',
    name: 'Prajogo Pangestu',
    descriptor: 'Founder — Barito Pacific Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Prajogo Pangestu founded Indonesia\'s Barito Pacific Group, a conglomerate spanning petrochemicals, energy, and mining.' }],
    rarity: 'epic',
    country: 'Indonesia',
    sourceConfidence: 'verified',
  },
  'nadhmi-auchi': {
    slug: 'nadhmi-auchi',
    name: 'Nadhmi Auchi',
    descriptor: 'Founder — General Mediterranean Holding',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Nadhmi Auchi is a British-Iraqi billionaire who founded and chairs General Mediterranean Holding, a diversified conglomerate.' }],
    rarity: 'rare',
    country: 'Iraq',
    sourceConfidence: 'verified',
  },
  'gil-shwed': {
    slug: 'gil-shwed',
    name: 'Gil Shwed',
    descriptor: 'Founder — Check Point Software Technologies',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Gil Shwed co-founded the Israeli cybersecurity company Check Point Software Technologies in 1993 and serves as its executive chairman.' }],
    rarity: 'rare',
    country: 'Israel',
    sourceConfidence: 'verified',
  },
  'tadashi-yanai': {
    slug: 'tadashi-yanai',
    name: 'Tadashi Yanai',
    descriptor: 'Founder — Fast Retailing (Uniqlo)',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Tadashi Yanai founded Fast Retailing, the parent company of Uniqlo, and is ranked by Forbes as Japan\'s richest person.' }],
    rarity: 'legendary',
    country: 'Japan',
    sourceConfidence: 'verified',
  },
  'amjad-masad': {
    slug: 'amjad-masad',
    name: 'Amjad Masad',
    descriptor: 'Founder — Replit',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Amjad Masad is a Jordanian-American entrepreneur who founded and serves as CEO of Replit, an online coding platform.' }],
    rarity: 'rare',
    country: 'Jordan',
    sourceConfidence: 'verified',
  },
  'vyacheslav-kim': {
    slug: 'vyacheslav-kim',
    name: 'Vyacheslav Kim',
    descriptor: 'Founder — Kaspi.kz',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Vyacheslav Kim co-founded Kaspi.kz in 2002, building it into Kazakhstan\'s largest fintech company.' }],
    rarity: 'rare',
    country: 'Kazakhstan',
    sourceConfidence: 'verified',
  },
  'nasser-al-kharafi': {
    slug: 'nasser-al-kharafi',
    name: 'Nasser Al-Kharafi',
    descriptor: 'CEO — M.A. Kharafi & Sons',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Nasser Al-Kharafi was a Kuwaiti businessman who chaired M.A. Kharafi & Sons, growing it to roughly $4.3 billion in sales.' }],
    rarity: 'rare',
    country: 'Kuwait',
    sourceConfidence: 'verified',
  },
  'najib-mikati': {
    slug: 'najib-mikati',
    name: 'Najib Mikati',
    descriptor: 'Founder — M1 Group / Investcom',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Najib Mikati co-founded telecommunications firm Investcom in 1982, later sold to MTN Group for $5.5 billion, and co-founded Beirut-based M1 Group.' }],
    rarity: 'rare',
    country: 'Lebanon',
    sourceConfidence: 'verified',
  },
  'robert-kuok': {
    slug: 'robert-kuok',
    name: 'Robert Kuok',
    descriptor: 'Founder — Kuok Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Robert Kuok founded Kuok Group in 1949 and later established the Shangri-La Hotels chain, and is ranked by Forbes as Malaysia\'s richest person.' }],
    rarity: 'rare',
    country: 'Malaysia',
    sourceConfidence: 'verified',
  },
  'qasim-ibrahim': {
    slug: 'qasim-ibrahim',
    name: 'Qasim Ibrahim',
    descriptor: 'Founder — Villa Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Qasim Ibrahim founded Villa Shipping & Trading Company in 1986, growing it into the Villa Group conglomerate spanning tourism and trade.' }],
    rarity: 'rare',
    country: 'Maldives',
    sourceConfidence: 'verified',
  },
  'odjargal-jambaljamts': {
    slug: 'odjargal-jambaljamts',
    name: 'Odjargal Jambaljamts',
    descriptor: 'Founder — Mongolian Mining Corporation (MCS Group)',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Odjargal Jambaljamts has chaired MCS Group since 1993 and served as executive chairman of Mongolian Mining Corporation.' }],
    rarity: 'rare',
    country: 'Mongolia',
    sourceConfidence: 'verified',
  },
  'serge-pun': {
    slug: 'serge-pun',
    name: 'Serge Pun',
    descriptor: 'Founder — Yoma Strategic Holdings',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Serge Pun founded Serge Pun & Associates in 1983 and chairs Yoma Strategic Holdings, a major Myanmar-focused conglomerate.' }],
    rarity: 'rare',
    country: 'Myanmar',
    sourceConfidence: 'verified',
  },
  'binod-chaudhary': {
    slug: 'binod-chaudhary',
    name: 'Binod Chaudhary',
    descriptor: 'Founder — Chaudhary Group (CG Corp Global)',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Binod Chaudhary chairs the Chaudhary Group and was named Nepal\'s first billionaire by Forbes in 2013.' }],
    rarity: 'rare',
    country: 'Nepal',
    sourceConfidence: 'verified',
  },
  'sheikh-suhail-bahwan': {
    slug: 'sheikh-suhail-bahwan',
    name: 'Sheikh Suhail Bahwan',
    descriptor: 'Founder — Suhail Bahwan Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Sheikh Suhail Bahwan founded the Suhail Bahwan Group in 1965, growing it into one of Oman\'s largest conglomerates.' }],
    rarity: 'rare',
    country: 'Oman',
    sourceConfidence: 'verified',
  },
  'mian-muhammad-mansha': {
    slug: 'mian-muhammad-mansha',
    name: 'Mian Muhammad Mansha',
    descriptor: 'Founder — Nishat Group / MCB Bank',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Mian Muhammad Mansha built the Nishat Group conglomerate and chairs MCB Bank, becoming the first Pakistani listed on the Forbes rich list.' }],
    rarity: 'rare',
    country: 'Pakistan',
    sourceConfidence: 'verified',
  },
  'munib-al-masri': {
    slug: 'munib-al-masri',
    name: 'Munib al-Masri',
    descriptor: 'Founder — Palestine Development and Investment Company (PADICO)',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Munib al-Masri, often described as the wealthiest Palestinian, founded the oil-and-gas contractor Edgo and chairs PADICO.' }],
    rarity: 'rare',
    country: 'Palestine',
    sourceConfidence: 'verified',
  },
  'enrique-razon-jr': {
    slug: 'enrique-razon-jr',
    name: 'Enrique Razon Jr.',
    descriptor: 'CEO — International Container Terminal Services (ICTSI)',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Enrique Razon Jr. is chairman and CEO of ICTSI and topped the Philippines\' richest list on Forbes\' 2026 billionaires ranking.' }],
    rarity: 'rare',
    country: 'Philippines',
    sourceConfidence: 'verified',
  },
  'sheikh-hamad-bin-jassim-bin-jaber-al-thani': {
    slug: 'sheikh-hamad-bin-jassim-bin-jaber-al-thani',
    name: 'Sheikh Hamad bin Jassim bin Jaber Al Thani',
    descriptor: 'Investor — Al Mirqab Capital',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Sheikh Hamad bin Jassim, Qatar\'s former prime minister and chairman of the Qatar Investment Authority, now owns the family investment vehicle Al Mirqab Capital.' }],
    rarity: 'rare',
    country: 'Qatar',
    sourceConfidence: 'verified',
  },
  'prince-alwaleed-bin-talal': {
    slug: 'prince-alwaleed-bin-talal',
    name: 'Prince Alwaleed bin Talal',
    descriptor: 'Founder — Kingdom Holding Company',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Prince Alwaleed bin Talal founded Kingdom Holding Company in 1980, holding stakes in Four Seasons, X, and other global companies.' }],
    rarity: 'epic',
    country: 'Saudi Arabia',
    sourceConfidence: 'verified',
  },
  'forrest-li': {
    slug: 'forrest-li',
    name: 'Forrest Li',
    descriptor: 'CEO — Sea Limited',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Forrest Li founded Sea Limited in 2009 and serves as its chairman and group CEO, overseeing Shopee and Garena.' }],
    rarity: 'rare',
    country: 'Singapore',
    sourceConfidence: 'verified',
  },
  'lee-jae-yong': {
    slug: 'lee-jae-yong',
    name: 'Lee Jae-yong',
    descriptor: 'CEO — Samsung Electronics',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Lee Jae-yong has led Samsung group since 2014 and was named executive chairman of Samsung Electronics in 2022.' }],
    rarity: 'epic',
    country: 'South Korea',
    sourceConfidence: 'verified',
  },
  'dhammika-perera': {
    slug: 'dhammika-perera',
    name: 'Dhammika Perera',
    descriptor: 'Founder — Vallibel One / Hayleys',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Dhammika Perera founded the Vallibel One conglomerate and holds a controlling stake in Hayleys.' }],
    rarity: 'rare',
    country: 'Sri Lanka',
    sourceConfidence: 'verified',
  },
  'rami-makhlouf': {
    slug: 'rami-makhlouf',
    name: 'Rami Makhlouf',
    descriptor: 'Founder — Syriatel',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Rami Makhlouf founded and was majority owner of Syriatel, Syria\'s largest mobile telecom operator.' }],
    rarity: 'rare',
    country: 'Syria',
    sourceConfidence: 'verified',
  },
  'dhanin-chearavanont': {
    slug: 'dhanin-chearavanont',
    name: 'Dhanin Chearavanont',
    descriptor: 'CEO — Charoen Pokphand (CP) Group',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Dhanin Chearavanont led the Charoen Pokphand Group for decades, expanding it into Thailand\'s largest private company.' }],
    rarity: 'rare',
    country: 'Thailand',
    sourceConfidence: 'verified',
  },
  'murat-ulker': {
    slug: 'murat-ulker',
    name: 'Murat Ulker',
    descriptor: 'CEO — Yildiz Holding',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Murat Ulker served as CEO of Yildiz Holding before becoming its chairman, and has repeatedly topped Forbes\' list of Turkey\'s wealthiest people.' }],
    rarity: 'epic',
    country: 'Turkey',
    sourceConfidence: 'verified',
  },
  'sultan-ahmed-bin-sulayem': {
    slug: 'sultan-ahmed-bin-sulayem',
    name: 'Sultan Ahmed bin Sulayem',
    descriptor: 'CEO — DP World',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Sultan Ahmed bin Sulayem is chairman and CEO of DP World, the Dubai-based global ports and logistics company.' }],
    rarity: 'rare',
    country: 'United Arab Emirates',
    sourceConfidence: 'verified',
  },
  'alisher-usmanov': {
    slug: 'alisher-usmanov',
    name: 'Alisher Usmanov',
    descriptor: 'Founder — USM Holdings',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Alisher Usmanov, born in the Uzbek SSR, founded USM Holdings and was first listed by Forbes in 2025 representing Uzbekistan.' }],
    rarity: 'common',
    country: 'Uzbekistan',
    sourceConfidence: 'uncertain',
  },
  'pham-nhat-vuong': {
    slug: 'pham-nhat-vuong',
    name: 'Pham Nhat Vuong',
    descriptor: 'Founder — Vingroup',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Pham Nhat Vuong founded and chairs Vingroup, Vietnam\'s largest private conglomerate, and also serves as CEO of its EV unit VinFast.' }],
    rarity: 'rare',
    country: 'Vietnam',
    sourceConfidence: 'verified',
  },
  'hayel-saeed-anam': {
    slug: 'hayel-saeed-anam',
    name: 'Hayel Saeed Anam',
    descriptor: 'Founder — Hayel Saeed Anam Group (HSA Group)',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Hayel Saeed Anam founded the HSA Group in 1938, which grew into Yemen\'s largest private conglomerate.' }],
    rarity: 'rare',
    country: 'Yemen',
    sourceConfidence: 'verified',
  },
  'benoni-urey': {
    slug: 'benoni-urey',
    name: 'Benoni Urey',
    descriptor: 'Founder — Lonestar Communications Corporation',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Benoni Urey founded Lonestar Communications Corporation and was described by The Economist as Liberia\'s wealthiest man in 2014.' }],
    rarity: 'rare',
    country: 'Liberia',
    sourceConfidence: 'verified',
  },
  'hesham-husni-bey': {
    slug: 'hesham-husni-bey',
    name: 'Hesham Husni Bey',
    descriptor: 'CEO — HB Group',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Hesham Husni Bey heads Libya\'s HB Group, a conglomerate holding shareholdings in most Libyan banks.' }],
    rarity: 'rare',
    country: 'Libya',
    sourceConfidence: 'verified',
  },
  'ylias-akbaraly': {
    slug: 'ylias-akbaraly',
    name: 'Ylias Akbaraly',
    descriptor: 'Founder — Sipromad Group (Redland)',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Ylias Akbaraly chairs Redland, holding company controlling Madagascar\'s Sipromad Group; Forbes called him Madagascar\'s richest man.' }],
    rarity: 'rare',
    country: 'Madagascar',
    sourceConfidence: 'verified',
  },
  'thom-mpinganjira': {
    slug: 'thom-mpinganjira',
    name: 'Thom Mpinganjira',
    descriptor: 'Founder — FDH Bank',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Thom Mpinganjira founded FDH Bank in Blantyre and became Malawi\'s first dollar billionaire.' }],
    rarity: 'rare',
    country: 'Malawi',
    sourceConfidence: 'verified',
  },
  'mamadou-sinsy-coulibaly': {
    slug: 'mamadou-sinsy-coulibaly',
    name: 'Mamadou Sinsy Coulibaly',
    descriptor: 'Founder — Kledu Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Mamadou Sinsy Coulibaly founded and leads Mali\'s Kledu Group, operating more than fifty companies.' }],
    rarity: 'rare',
    country: 'Mali',
    sourceConfidence: 'verified',
  },
  'mohamed-ould-bouamatou': {
    slug: 'mohamed-ould-bouamatou',
    name: 'Mohamed Ould Bouamatou',
    descriptor: 'Founder — BSA Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Mohamed Ould Bouamatou founded Generale de Banque de Mauritanie and heads the BSA Group conglomerate.' }],
    rarity: 'rare',
    country: 'Mauritania',
    sourceConfidence: 'verified',
  },
  'arnaud-lagesse': {
    slug: 'arnaud-lagesse',
    name: 'Arnaud Lagesse',
    descriptor: 'CEO — IBL Ltd',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Arnaud Lagesse is Group CEO of IBL Ltd, the largest business conglomerate in Mauritius.' }],
    rarity: 'rare',
    country: 'Mauritius',
    sourceConfidence: 'verified',
  },
  'othman-benjelloun': {
    slug: 'othman-benjelloun',
    name: 'Othman Benjelloun',
    descriptor: 'CEO — Bank of Africa (formerly BMCE Bank)',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Othman Benjelloun is chairman and CEO of Bank of Africa and was ranked Morocco\'s wealthiest person by Forbes in 2026.' }],
    rarity: 'rare',
    country: 'Morocco',
    sourceConfidence: 'verified',
  },
  'salimo-abdula': {
    slug: 'salimo-abdula',
    name: 'Salimo Abdula',
    descriptor: 'Founder — Intelec Holdings Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Salimo Abdula founded Intelec Holdings Group in 1997 and chairs Vodacom Mozambique\'s board.' }],
    rarity: 'rare',
    country: 'Mozambique',
    sourceConfidence: 'verified',
  },
  'sven-thieme': {
    slug: 'sven-thieme',
    name: 'Sven Thieme',
    descriptor: 'Investor — Ohlthaver & List Group',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Sven Thieme chairs Ohlthaver & List, described as the largest private company in Namibia.' }],
    rarity: 'rare',
    country: 'Namibia',
    sourceConfidence: 'verified',
  },
  'aliko-dangote': {
    slug: 'aliko-dangote',
    name: 'Aliko Dangote',
    descriptor: 'Founder — Dangote Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Aliko Dangote founded and chairs Dangote Group, including Dangote Cement and the Dangote Oil Refinery, and is ranked Africa\'s richest person by Forbes.' }],
    rarity: 'legendary',
    country: 'Nigeria',
    sourceConfidence: 'verified',
  },
  'tribert-rujugiro-ayabatwa': {
    slug: 'tribert-rujugiro-ayabatwa',
    name: 'Tribert Rujugiro Ayabatwa',
    descriptor: 'Founder — Pan African Tobacco Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Tribert Rujugiro Ayabatwa founded the Pan African Tobacco Group, Africa\'s largest tobacco company.' }],
    rarity: 'rare',
    country: 'Rwanda',
    sourceConfidence: 'verified',
  },
  'yerim-sow': {
    slug: 'yerim-sow',
    name: 'Yerim Sow',
    descriptor: 'Founder — Teyliom Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Yerim Sow founded Teyliom Group and is identified as Senegal\'s richest businessman, with a fortune over $500 million.' }],
    rarity: 'rare',
    country: 'Senegal',
    sourceConfidence: 'verified',
  },
  'mukesh-valabhji': {
    slug: 'mukesh-valabhji',
    name: 'Mukesh Valabhji',
    descriptor: 'Investor — Capital Management Group',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Mukesh Valabhji is a Seychellois entrepreneur who has owned and chaired the Capital Management Group since 2006.' }],
    rarity: 'rare',
    country: 'Seychelles',
    sourceConfidence: 'verified',
  },
  'hisham-mackie': {
    slug: 'hisham-mackie',
    name: 'Hisham Mackie',
    descriptor: 'Founder — H.M Diamond',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Hisham Mackie\'s company accounts for 51% of Sierra Leone\'s official diamond exports.' }],
    rarity: 'rare',
    country: 'Sierra Leone',
    sourceConfidence: 'verified',
  },
  'abdirashid-duale': {
    slug: 'abdirashid-duale',
    name: 'Abdirashid Duale',
    descriptor: 'CEO — Dahabshiil',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Abdirashid Duale is CEO of Dahabshiil, a Somali international money transfer company he took over from his father.' }],
    rarity: 'rare',
    country: 'Somalia',
    sourceConfidence: 'verified',
  },
  'johann-rupert': {
    slug: 'johann-rupert',
    name: 'Johann Rupert',
    descriptor: 'Investor — Compagnie Financiere Richemont',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Johann Rupert is chairman of Compagnie Financiere Richemont, the Swiss luxury group owning Cartier and Montblanc, and South Africa\'s richest person.' }],
    rarity: 'epic',
    country: 'South Africa',
    sourceConfidence: 'verified',
  },
  'mo-ibrahim': {
    slug: 'mo-ibrahim',
    name: 'Mo Ibrahim',
    descriptor: 'Founder — Celtel',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Mo Ibrahim is a Sudanese-British businessman who founded mobile phone operator Celtel, sold in 2005 for $3.4 billion.' }],
    rarity: 'rare',
    country: 'Sudan',
    sourceConfidence: 'verified',
  },
  'mohammed-dewji': {
    slug: 'mohammed-dewji',
    name: 'Mohammed Dewji',
    descriptor: 'CEO — MeTL Group',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Mohammed Dewji is CEO of MeTL Group; Forbes ranks him as Tanzania\'s richest person.' }],
    rarity: 'rare',
    country: 'Tanzania',
    sourceConfidence: 'verified',
  },
  'gervais-djondo': {
    slug: 'gervais-djondo',
    name: 'Gervais Djondo',
    descriptor: 'Founder — Ecobank / ASKY Airlines',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Gervais Djondo co-founded Ecobank and founded ASKY Airlines.' }],
    rarity: 'rare',
    country: 'Togo',
    sourceConfidence: 'verified',
  },
  'marouan-mabrouk': {
    slug: 'marouan-mabrouk',
    name: 'Marouan Mabrouk',
    descriptor: 'Investor — Groupe Mabrouk',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Marouan Mabrouk, with his brothers, controls a 38.6% stake in BIAT through the family\'s Groupe Mabrouk conglomerate.' }],
    rarity: 'rare',
    country: 'Tunisia',
    sourceConfidence: 'verified',
  },
  'sudhir-ruparelia': {
    slug: 'sudhir-ruparelia',
    name: 'Sudhir Ruparelia',
    descriptor: 'Founder — Ruparelia Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Sudhir Ruparelia is chairman of Ruparelia Group and became Uganda\'s first dollar billionaire in 2014.' }],
    rarity: 'rare',
    country: 'Uganda',
    sourceConfidence: 'verified',
  },
  'hakainde-hichilema': {
    slug: 'hakainde-hichilema',
    name: 'Hakainde Hichilema',
    descriptor: 'Investor — Grant Thornton Zambia',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Before becoming President of Zambia, Hakainde Hichilema was CEO of Grant Thornton Zambia and built one of the country\'s largest cattle-ranching operations.' }],
    rarity: 'common',
    country: 'Zambia',
    sourceConfidence: 'uncertain',
  },
  'strive-masiyiwa': {
    slug: 'strive-masiyiwa',
    name: 'Strive Masiyiwa',
    descriptor: 'Founder — Econet Wireless',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Strive Masiyiwa founded Econet Wireless in 1993 and is ranked by Forbes as Zimbabwe\'s richest person.' }],
    rarity: 'rare',
    country: 'Zimbabwe',
    sourceConfidence: 'verified',
  },
  'issad-rebrab': {
    slug: 'issad-rebrab',
    name: 'Issad Rebrab',
    descriptor: 'Founder — Cevital',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Issad Rebrab founded Cevital in 1998, building it into Algeria\'s largest private company spanning sugar, agribusiness, and steel.' }],
    rarity: 'rare',
    country: 'Algeria',
    sourceConfidence: 'verified',
  },
  'isabel-dos-santos': {
    slug: 'isabel-dos-santos',
    name: 'Isabel dos Santos',
    descriptor: 'Founder — Unitel',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Isabel dos Santos co-founded Angolan telecom operator Unitel in 1998 and was widely described as Africa\'s first female billionaire.' }],
    rarity: 'rare',
    country: 'Angola',
    sourceConfidence: 'verified',
  },
  'sebastien-ajavon': {
    slug: 'sebastien-ajavon',
    name: 'Sebastien Ajavon',
    descriptor: 'Founder — Cajaf-Comon',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Sebastien Ajavon founded Cajaf-Comon, becoming Benin\'s largest importer of frozen poultry.' }],
    rarity: 'rare',
    country: 'Benin',
    sourceConfidence: 'verified',
  },
  'ramachandran-ottapathu': {
    slug: 'ramachandran-ottapathu',
    name: 'Ramachandran Ottapathu',
    descriptor: 'CEO — Choppies Enterprises',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Ramachandran Ottapathu is CEO of Choppies Enterprises, Botswana\'s largest retail chain.' }],
    rarity: 'rare',
    country: 'Botswana',
    sourceConfidence: 'verified',
  },
  'mahamadou-bonkoungou': {
    slug: 'mahamadou-bonkoungou',
    name: 'Mahamadou Bonkoungou',
    descriptor: 'Founder — EBOMAF',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Mahamadou Bonkoungou founded the EBOMAF group in 1988, one of West Africa\'s largest private construction companies.' }],
    rarity: 'rare',
    country: 'Burkina Faso',
    sourceConfidence: 'verified',
  },
  'adrien-ntigacika': {
    slug: 'adrien-ntigacika',
    name: 'Adrien Ntigacika',
    descriptor: 'Founder — ITRACOM Holding',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Adrien Ntigacika founded the ITRACOM group, whose FOMI subsidiary became Burundi\'s first large-scale fertilizer manufacturer.' }],
    rarity: 'rare',
    country: 'Burundi',
    sourceConfidence: 'verified',
  },
  'baba-ahmadou-danpullo': {
    slug: 'baba-ahmadou-danpullo',
    name: 'Baba Ahmadou Danpullo',
    descriptor: 'Founder — Bestinver Group / Ndawara Tea Estate',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Baba Ahmadou Danpullo built a business empire spanning tea, cattle, and telecom, ranked richest in francophone sub-Saharan Africa by Forbes Africa.' }],
    rarity: 'rare',
    country: 'Cameroon',
    sourceConfidence: 'verified',
  },
  'joseph-ichame-kamach': {
    slug: 'joseph-ichame-kamach',
    name: 'Joseph Ichame Kamach',
    descriptor: 'Founder — Groupe Kamach',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Joseph Ichame Kamach founded Groupe Kamach in 1972, one of the CAR\'s largest private employers.' }],
    rarity: 'common',
    country: 'Central African Republic',
    sourceConfidence: 'uncertain',
  },
  'claude-wilfrid-etoka': {
    slug: 'claude-wilfrid-etoka',
    name: 'Claude Wilfrid Etoka',
    descriptor: 'CEO — SARPD Oil',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Claude Wilfrid Etoka founded and serves as CEO of SARPD Oil, controlling a majority share of Congo\'s fuel imports.' }],
    rarity: 'rare',
    country: 'Congo (Republic of the)',
    sourceConfidence: 'verified',
  },
  'moise-katumbi': {
    slug: 'moise-katumbi',
    name: 'Moise Katumbi',
    descriptor: 'Founder — Mining Company Katanga (MCK)',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Moise Katumbi co-founded Mining Company Katanga (MCK), turning a family fishing business into a mining and logistics empire.' }],
    rarity: 'rare',
    country: 'Congo (Democratic Republic of the)',
    sourceConfidence: 'verified',
  },
  'jean-louis-billon': {
    slug: 'jean-louis-billon',
    name: 'Jean-Louis Billon',
    descriptor: 'CEO — SIFCA Group',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Jean-Louis Billon served as CEO of the SIFCA Group, West Africa\'s largest agro-industrial conglomerate.' }],
    rarity: 'rare',
    country: 'Cote d\'Ivoire',
    sourceConfidence: 'verified',
  },
  'abdourahman-boreh': {
    slug: 'abdourahman-boreh',
    name: 'Abdourahman Boreh',
    descriptor: 'Investor — Soprim Construction',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Abdourahman Boreh was the largest private investor behind the development of the Doraleh port complex in Djibouti.' }],
    rarity: 'rare',
    country: 'Djibouti',
    sourceConfidence: 'verified',
  },
  'nassef-sawiris': {
    slug: 'nassef-sawiris',
    name: 'Nassef Sawiris',
    descriptor: 'CEO — OCI N.V.',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Nassef Sawiris runs OCI N.V., one of the world\'s largest nitrogen fertilizer producers, and is Forbes\' richest Egyptian.' }],
    rarity: 'rare',
    country: 'Egypt',
    sourceConfidence: 'verified',
  },
  'nathan-kirsh': {
    slug: 'nathan-kirsh',
    name: 'Nathan Kirsh',
    descriptor: 'Founder — Kirsh Group / Jetro Holdings',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Nathan Kirsh built the Kirsh Group, including New York-based Jetro Holdings, starting from a corn-milling business founded in Eswatini in 1958.' }],
    rarity: 'rare',
    country: 'Eswatini',
    sourceConfidence: 'verified',
  },
  'mohammed-al-amoudi': {
    slug: 'mohammed-al-amoudi',
    name: 'Mohammed Al Amoudi',
    descriptor: 'Founder — MIDROC',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Mohammed Al Amoudi founded the MIDROC conglomerate and is Ethiopia\'s largest single foreign investor.' }],
    rarity: 'rare',
    country: 'Ethiopia',
    sourceConfidence: 'verified',
  },
  'christian-kerangall': {
    slug: 'christian-kerangall',
    name: 'Christian Kerangall',
    descriptor: 'Founder — Sogafric Holding',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Christian Kerangall chairs Sogafric Holding, a diversified conglomerate widely reported as Gabon\'s richest business group.' }],
    rarity: 'common',
    country: 'Gabon',
    sourceConfidence: 'uncertain',
  },
  'muhammed-jah': {
    slug: 'muhammed-jah',
    name: 'Muhammed Jah',
    descriptor: 'Founder — QuantumNet Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Muhammed Jah founded QuantumNet, the Gambia\'s first internet service provider, building it into one of the country\'s largest conglomerates.' }],
    rarity: 'rare',
    country: 'Gambia',
    sourceConfidence: 'verified',
  },
  'sam-jonah': {
    slug: 'sam-jonah',
    name: 'Sam Jonah',
    descriptor: 'CEO — Ashanti Goldfields / Jonah Capital',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Sam Jonah served as CEO of Ashanti Goldfields Company and engineered its 2004 merger into AngloGold Ashanti; now chairs Jonah Capital.' }],
    rarity: 'rare',
    country: 'Ghana',
    sourceConfidence: 'verified',
  },
  'fadi-wazni': {
    slug: 'fadi-wazni',
    name: 'Fadi Wazni',
    descriptor: 'CEO — United Mining Supply Company',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Fadi Wazni is CEO of United Mining Supply Company and a founder of the SMB-Winning Consortium, a major bauxite mining group in Guinea.' }],
    rarity: 'common',
    country: 'Guinea',
    sourceConfidence: 'uncertain',
  },
  'carlos-gomes-junior': {
    slug: 'carlos-gomes-junior',
    name: 'Carlos Gomes Junior',
    descriptor: 'Investor',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Carlos Gomes Junior is a banker and businessman widely reported as one of Guinea-Bissau\'s richest men, though better known for his political career.' }],
    rarity: 'common',
    country: 'Guinea-Bissau',
    sourceConfidence: 'uncertain',
  },
  'james-mwangi': {
    slug: 'james-mwangi',
    name: 'James Mwangi',
    descriptor: 'CEO — Equity Group Holdings',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'James Mwangi is group managing director and CEO of Equity Group Holdings, one of East Africa\'s largest banking groups.' }],
    rarity: 'rare',
    country: 'Kenya',
    sourceConfidence: 'verified',
  },
  'sam-matekane': {
    slug: 'sam-matekane',
    name: 'Sam Matekane',
    descriptor: 'Founder — Matekane Group of Companies',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Sam Matekane founded the Matekane Group of Companies in 1986, spanning construction, diamond mining, and aviation.' }],
    rarity: 'rare',
    country: 'Lesotho',
    sourceConfidence: 'verified',
  },
  'george-ryan': {
    slug: 'george-ryan',
    name: 'George Ryan',
    descriptor: 'Founder — Ryan\'s Construction / Ryan Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'George Ryan founded Ryan\'s Construction in Antigua in 1965, growing it into one of the country\'s largest business groups.' }],
    rarity: 'rare',
    country: 'Antigua and Barbuda',
    sourceConfidence: 'verified',
  },
  'joe-lewis': {
    slug: 'joe-lewis',
    name: 'Joe Lewis',
    descriptor: 'Investor — Tavistock Group',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Joe Lewis owns the Tavistock Group, a holding company with interests in over 200 businesses, and has been based in the Bahamas for decades.' }],
    rarity: 'rare',
    country: 'Bahamas',
    sourceConfidence: 'verified',
  },
  'joseph-nathaniel-goddard': {
    slug: 'joseph-nathaniel-goddard',
    name: 'Joseph Nathaniel Goddard',
    descriptor: 'Founder — Goddard Enterprises Limited',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Joseph Nathaniel Goddard founded Goddard Enterprises in Barbados in 1921; the conglomerate now operates across more than 20 countries.' }],
    rarity: 'rare',
    country: 'Barbados',
    sourceConfidence: 'verified',
  },
  'barry-bowen': {
    slug: 'barry-bowen',
    name: 'Barry Bowen',
    descriptor: 'CEO — Bowen and Bowen Ltd',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Barry Bowen led Bowen and Bowen Ltd, Belize\'s exclusive Coca-Cola bottler, turning Belikin into Belize\'s dominant beer brand.' }],
    rarity: 'rare',
    country: 'Belize',
    sourceConfidence: 'verified',
  },
  'tobias-lutke': {
    slug: 'tobias-lutke',
    name: 'Tobias Lutke',
    descriptor: 'CEO — Shopify',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Tobias Lutke co-founded and serves as CEO of Shopify, the Ottawa-headquartered e-commerce platform he started in 2006.' }],
    rarity: 'epic',
    country: 'Canada',
    sourceConfidence: 'verified',
  },
  'francis-durman-esquivel': {
    slug: 'francis-durman-esquivel',
    name: 'Francis Durman Esquivel',
    descriptor: 'Founder — Grupo Montecristo',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Francis Durman Esquivel, president of Grupo Montecristo, is the only Costa Rican to appear on the Forbes Mexico Central America rich list, valued around $400 million.' }],
    rarity: 'common',
    country: 'Costa Rica',
    sourceConfidence: 'uncertain',
  },
  'albert-cavendish-shillingford': {
    slug: 'albert-cavendish-shillingford',
    name: 'Albert Cavendish Shillingford',
    descriptor: 'Founder — A.C. Shillingford & Co',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'A.C. Shillingford founded a diversified conglomerate spanning retail, insurance, and lime processing in Dominica.' }],
    rarity: 'rare',
    country: 'Dominica',
    sourceConfidence: 'verified',
  },
  'felipe-vicini-lluberes': {
    slug: 'felipe-vicini-lluberes',
    name: 'Felipe Vicini Lluberes',
    descriptor: 'Investor — Grupo Vicini',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Felipe Vicini Lluberes is a leading member of the Vicini family, widely documented as the wealthiest family in the Dominican Republic.' }],
    rarity: 'rare',
    country: 'Dominican Republic',
    sourceConfidence: 'verified',
  },
  'ricardo-poma': {
    slug: 'ricardo-poma',
    name: 'Ricardo Poma',
    descriptor: 'CEO — Grupo Poma',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Ricardo Poma was CEO of Grupo Poma, a San Salvador-based conglomerate spanning real estate, automotive, and hospitality.' }],
    rarity: 'rare',
    country: 'El Salvador',
    sourceConfidence: 'verified',
  },
  'juan-jose-gutierrez': {
    slug: 'juan-jose-gutierrez',
    name: 'Juan Jose Gutierrez',
    descriptor: 'CEO — Corporacion Multi-Inversiones (CMI)',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Juan Jose Gutierrez chairs CMI Foods; Forbes estimates the owning Gutierrez family\'s conglomerate at about $3 billion.' }],
    rarity: 'rare',
    country: 'Guatemala',
    sourceConfidence: 'verified',
  },
  'gilbert-bigio': {
    slug: 'gilbert-bigio',
    name: 'Gilbert Bigio',
    descriptor: 'Founder — GB Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Gilbert Bigio founded GB Group in 1972, becoming known as Haiti\'s first billionaire.' }],
    rarity: 'rare',
    country: 'Haiti',
    sourceConfidence: 'verified',
  },
  'fredy-nasser': {
    slug: 'fredy-nasser',
    name: 'Fredy Nasser',
    descriptor: 'Founder — Grupo Terra',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Fredy Nasser founded Grupo Terra in 2000, a Honduran conglomerate spanning energy and fuel distribution.' }],
    rarity: 'rare',
    country: 'Honduras',
    sourceConfidence: 'verified',
  },
  'michael-lee-chin': {
    slug: 'michael-lee-chin',
    name: 'Michael Lee-Chin',
    descriptor: 'CEO — Portland Holdings Inc.',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Michael Lee-Chin is chairman and CEO of Portland Holdings and has chaired NCB Financial Group, Jamaica\'s National Commercial Bank, since 2002.' }],
    rarity: 'rare',
    country: 'Jamaica',
    sourceConfidence: 'verified',
  },
  'carlos-slim-helu': {
    slug: 'carlos-slim-helu',
    name: 'Carlos Slim Helu',
    descriptor: 'Investor — America Movil / Grupo Carso',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Carlos Slim Helu holds a roughly 57% stake in America Movil, Latin America\'s largest mobile telecom company, and controls Grupo Carso.' }],
    rarity: 'legendary',
    country: 'Mexico',
    sourceConfidence: 'verified',
  },
  'carlos-pellas': {
    slug: 'carlos-pellas',
    name: 'Carlos Pellas',
    descriptor: 'Investor — Grupo Pellas',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Carlos Pellas is the controlling shareholder of Grupo Pellas, Nicaragua\'s largest private conglomerate, named the country\'s first billionaire by Bloomberg.' }],
    rarity: 'rare',
    country: 'Nicaragua',
    sourceConfidence: 'verified',
  },
  'stanley-motta': {
    slug: 'stanley-motta',
    name: 'Stanley Motta',
    descriptor: 'Investor — MKH Capital Partners',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Stanley Motta holds stakes in Copa Airlines, Banco General, and insurer ASSA through MKH Capital Partners and Motta Internacional.' }],
    rarity: 'rare',
    country: 'Panama',
    sourceConfidence: 'verified',
  },
  'joseph-quentin-charles': {
    slug: 'joseph-quentin-charles',
    name: 'Joseph Quentin Charles',
    descriptor: 'Founder — JQ Charles Group of Companies',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Joseph Quentin Charles founded JQ Charles Ltd. in Castries in 1944, growing it into one of Saint Lucia\'s largest locally-owned conglomerates.' }],
    rarity: 'common',
    country: 'Saint Lucia',
    sourceConfidence: 'uncertain',
  },
  'anthony-n-sabga': {
    slug: 'anthony-n-sabga',
    name: 'Anthony N. Sabga',
    descriptor: 'CEO — ANSA McAL Limited',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Anthony Norman Sabga led the Sabga family\'s expansion of ANSA McAL Limited, Trinidad and Tobago\'s largest conglomerate.' }],
    rarity: 'rare',
    country: 'Trinidad and Tobago',
    sourceConfidence: 'verified',
  },
  'elon-musk': {
    slug: 'elon-musk',
    name: 'Elon Musk',
    descriptor: 'CEO — Tesla / SpaceX',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Elon Musk has served as CEO of Tesla since 2008 and founded SpaceX in 2002.' }],
    rarity: 'legendary',
    country: 'United States',
    sourceConfidence: 'verified',
  },
  'samir-mane': {
    slug: 'samir-mane',
    name: 'Samir Mane',
    descriptor: 'Founder — Balfin Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Samir Mane founded the Balkan Finance Investment Group (Balfin) in 1993 and became Albania\'s first Forbes-listed billionaire in 2025.' }],
    rarity: 'rare',
    country: 'Albania',
    sourceConfidence: 'verified',
  },
  'maria-reig-moles': {
    slug: 'maria-reig-moles',
    name: 'Maria Reig Moles',
    descriptor: 'CEO — Reig Capital Group',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Maria Reig Moles is president of the Reig Capital Group, a family-owned Andorran financial and banking conglomerate she inherited in 1979.' }],
    rarity: 'common',
    country: 'Andorra',
    sourceConfidence: 'uncertain',
  },
  'dietrich-mateschitz': {
    slug: 'dietrich-mateschitz',
    name: 'Dietrich Mateschitz',
    descriptor: 'Founder — Red Bull GmbH',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Dietrich Mateschitz co-founded Red Bull GmbH in 1984, launching the energy drink in Austria in 1987.' }],
    rarity: 'rare',
    country: 'Austria',
    sourceConfidence: 'verified',
  },
  'viktor-prokopenya': {
    slug: 'viktor-prokopenya',
    name: 'Viktor Prokopenya',
    descriptor: 'Founder — VP Capital / Capital.com',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Viktor Prokopenya, born in Minsk, founded the fintech trading platform Capital.com and investment vehicle VP Capital.' }],
    rarity: 'rare',
    country: 'Belarus',
    sourceConfidence: 'verified',
  },
  'alexandre-van-damme': {
    slug: 'alexandre-van-damme',
    name: 'Alexandre Van Damme',
    descriptor: 'Investor — AB InBev',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Alexandre Van Damme has served as a director of AB InBev since 1992 and is one of Belgium\'s wealthiest people.' }],
    rarity: 'rare',
    country: 'Belgium',
    sourceConfidence: 'verified',
  },
  'boris-nemsic': {
    slug: 'boris-nemsic',
    name: 'Boris Nemsic',
    descriptor: 'CEO — Telekom Austria / VimpelCom',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Boris Nemsic, born in Sarajevo, served as CEO of Telekom Austria from 2006 to 2009 and later CEO of VimpelCom.' }],
    rarity: 'rare',
    country: 'Bosnia and Herzegovina',
    sourceConfidence: 'verified',
  },
  'vasil-bozhkov': {
    slug: 'vasil-bozhkov',
    name: 'Vasil Bozhkov',
    descriptor: 'Investor — New Games',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Vasil Bozhkov built a gambling and real-estate business empire that once made him Bulgaria\'s richest man.' }],
    rarity: 'rare',
    country: 'Bulgaria',
    sourceConfidence: 'verified',
  },
  'emil-tedeschi': {
    slug: 'emil-tedeschi',
    name: 'Emil Tedeschi',
    descriptor: 'Founder — Atlantic Grupa',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Emil Tedeschi founded Atlantic Grupa in 1991, one of Croatia\'s largest food and consumer-goods companies.' }],
    rarity: 'rare',
    country: 'Croatia',
    sourceConfidence: 'verified',
  },
  'petr-kellner': {
    slug: 'petr-kellner',
    name: 'Petr Kellner',
    descriptor: 'Founder — PPF Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Petr Kellner founded PPF Group in 1991, an international investment group operating in 25 countries, as the wealthiest Czech in history.' }],
    rarity: 'rare',
    country: 'Czech Republic',
    sourceConfidence: 'verified',
  },
  'kjeld-kirk-kristiansen': {
    slug: 'kjeld-kirk-kristiansen',
    name: 'Kjeld Kirk Kristiansen',
    descriptor: 'CEO — Lego Group',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Kjeld Kirk Kristiansen led the Lego Group as CEO from 1979 to 2004, and via Kirkbi remains Denmark\'s richest person.' }],
    rarity: 'rare',
    country: 'Denmark',
    sourceConfidence: 'verified',
  },
  'taavet-hinrikus': {
    slug: 'taavet-hinrikus',
    name: 'Taavet Hinrikus',
    descriptor: 'Founder — Wise',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Taavet Hinrikus co-founded the money-transfer company Wise in 2010, becoming one of Estonia\'s first billionaires.' }],
    rarity: 'rare',
    country: 'Estonia',
    sourceConfidence: 'verified',
  },
  'ilkka-paananen': {
    slug: 'ilkka-paananen',
    name: 'Ilkka Paananen',
    descriptor: 'CEO — Supercell',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Ilkka Paananen co-founded and serves as CEO of Supercell, the Helsinki-based mobile game studio behind Clash of Clans.' }],
    rarity: 'rare',
    country: 'Finland',
    sourceConfidence: 'verified',
  },
  'bernard-arnault': {
    slug: 'bernard-arnault',
    name: 'Bernard Arnault',
    descriptor: 'CEO — LVMH',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Bernard Arnault is chairman and CEO of LVMH, the world\'s largest luxury goods conglomerate, and has ranked among the world\'s richest people.' }],
    rarity: 'legendary',
    country: 'France',
    sourceConfidence: 'verified',
  },
  'dieter-schwarz': {
    slug: 'dieter-schwarz',
    name: 'Dieter Schwarz',
    descriptor: 'Founder — Schwarz Group (Lidl / Kaufland)',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Dieter Schwarz built the Schwarz Group into Europe\'s largest retailer and is Germany\'s wealthiest person.' }],
    rarity: 'legendary',
    country: 'Germany',
    sourceConfidence: 'verified',
  },
  'spiros-latsis': {
    slug: 'spiros-latsis',
    name: 'Spiros Latsis',
    descriptor: 'Investor — Latsis Group (Eurobank / Hellenic Petroleum)',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Spiros Latsis controls the Latsis Group\'s holdings, including major stakes in Eurobank and Hellenic Petroleum.' }],
    rarity: 'rare',
    country: 'Greece',
    sourceConfidence: 'verified',
  },
  'sandor-csanyi': {
    slug: 'sandor-csanyi',
    name: 'Sandor Csanyi',
    descriptor: 'CEO — OTP Bank',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Sandor Csanyi is chairman and CEO of OTP Bank, Hungary\'s largest bank, expanded under his leadership into an 11-country group.' }],
    rarity: 'rare',
    country: 'Hungary',
    sourceConfidence: 'verified',
  },
  'bjorgolfur-thor-bjorgolfsson': {
    slug: 'bjorgolfur-thor-bjorgolfsson',
    name: 'Bjorgolfur Thor Bjorgolfsson',
    descriptor: 'Founder — Novator Partners',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Bjorgolfur Thor Bjorgolfsson founded the investment firm Novator Partners and was, as of 2019, Iceland\'s only billionaire.' }],
    rarity: 'rare',
    country: 'Iceland',
    sourceConfidence: 'verified',
  },
  'michael-oleary': {
    slug: 'michael-oleary',
    name: 'Michael O\'Leary',
    descriptor: 'CEO — Ryanair',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Michael O\'Leary has served as group CEO of Ryanair since 1994, transforming it into Europe\'s largest low-cost airline.' }],
    rarity: 'rare',
    country: 'Ireland',
    sourceConfidence: 'verified',
  },
  'giovanni-ferrero': {
    slug: 'giovanni-ferrero',
    name: 'Giovanni Ferrero',
    descriptor: 'CEO — Ferrero SpA',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Giovanni Ferrero is executive chairman of Ferrero SpA, maker of Nutella and Ferrero Rocher, and is currently Italy\'s wealthiest person.' }],
    rarity: 'epic',
    country: 'Italy',
    sourceConfidence: 'verified',
  },
  'arnis-riekstins': {
    slug: 'arnis-riekstins',
    name: 'Arnis Riekstins',
    descriptor: 'Founder — MikroTik',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Arnis Riekstins co-founded MikroTik, the Riga-based networking equipment maker behind RouterOS, in 1996.' }],
    rarity: 'rare',
    country: 'Latvia',
    sourceConfidence: 'verified',
  },
  'hans-adam-ii': {
    slug: 'hans-adam-ii',
    name: 'Hans-Adam II',
    descriptor: 'Investor — LGT Group',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Prince Hans-Adam II expanded LGT Group into a global private-banking and asset-management firm with over $460 billion under management.' }],
    rarity: 'rare',
    country: 'Liechtenstein',
    sourceConfidence: 'verified',
  },
  'gediminas-ziemelis': {
    slug: 'gediminas-ziemelis',
    name: 'Gediminas Ziemelis',
    descriptor: 'Founder — Avia Solutions Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Gediminas Ziemelis founded and chairs Avia Solutions Group, an aviation services conglomerate, as Lithuania\'s richest person.' }],
    rarity: 'rare',
    country: 'Lithuania',
    sourceConfidence: 'verified',
  },
  'lakshmi-mittal': {
    slug: 'lakshmi-mittal',
    name: 'Lakshmi Mittal',
    descriptor: 'Founder — ArcelorMittal',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Lakshmi Mittal built ArcelorMittal into the world\'s largest steelmaker, headquartered in Luxembourg City.' }],
    rarity: 'rare',
    country: 'Luxembourg',
    sourceConfidence: 'verified',
  },
  'joe-gasan': {
    slug: 'joe-gasan',
    name: 'Joe Gasan',
    descriptor: 'CEO — Gasan Group',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Joe Gasan heads the Gasan Group, a Maltese conglomerate spanning car dealerships, insurance and banking.' }],
    rarity: 'common',
    country: 'Malta',
    sourceConfidence: 'uncertain',
  },
  'anatol-stati': {
    slug: 'anatol-stati',
    name: 'Anatol Stati',
    descriptor: 'Founder — Ascom Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Anatol Stati founded Ascom Group in 1994, leading the Moldovan oil-services conglomerate as its president and CEO.' }],
    rarity: 'rare',
    country: 'Moldova',
    sourceConfidence: 'verified',
  },
  'stefano-pessina': {
    slug: 'stefano-pessina',
    name: 'Stefano Pessina',
    descriptor: 'CEO — Walgreens Boots Alliance',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Stefano Pessina built his family\'s pharmaceutical distribution business into Walgreens Boots Alliance, which he chairs, and remains Monaco\'s wealthiest resident.' }],
    rarity: 'rare',
    country: 'Monaco',
    sourceConfidence: 'verified',
  },
  'aco-djukanovic': {
    slug: 'aco-djukanovic',
    name: 'Aco Djukanovic',
    descriptor: 'Investor — Monte Nova',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Aco Djukanovic built Monte Nova along with banking and real-estate holdings into one of Montenegro\'s largest private business empires.' }],
    rarity: 'common',
    country: 'Montenegro',
    sourceConfidence: 'uncertain',
  },
  'charlene-de-carvalho-heineken': {
    slug: 'charlene-de-carvalho-heineken',
    name: 'Charlene de Carvalho-Heineken',
    descriptor: 'Investor — Heineken N.V.',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Charlene de Carvalho-Heineken owns a 25% controlling interest in Heineken N.V., inherited from her father Freddy Heineken.' }],
    rarity: 'rare',
    country: 'Netherlands',
    sourceConfidence: 'verified',
  },
  'zhivko-mukaetov': {
    slug: 'zhivko-mukaetov',
    name: 'Zhivko Mukaetov',
    descriptor: 'CEO — Alkaloid AD Skopje',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Zhivko Mukaetov leads Alkaloid AD Skopje, North Macedonia\'s largest pharmaceutical company.' }],
    rarity: 'common',
    country: 'North Macedonia',
    sourceConfidence: 'uncertain',
  },
  'kjell-inge-rokke': {
    slug: 'kjell-inge-rokke',
    name: 'Kjell Inge Rokke',
    descriptor: 'Investor — Aker ASA',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Kjell Inge Rokke turned a fishing business into a controlling stake in Aker ASA, the Norwegian industrial conglomerate he chairs.' }],
    rarity: 'rare',
    country: 'Norway',
    sourceConfidence: 'verified',
  },
  'michal-solowow': {
    slug: 'michal-solowow',
    name: 'Michal Solowow',
    descriptor: 'Founder — Synthos',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Michal Solowow owns and chairs Synthos, Cersanit, and Barlinek, repeatedly topping Forbes\' list of Poland\'s richest people.' }],
    rarity: 'rare',
    country: 'Poland',
    sourceConfidence: 'verified',
  },
  'americo-amorim': {
    slug: 'americo-amorim',
    name: 'Americo Amorim',
    descriptor: 'Founder — Amorim Group / Corticeira Amorim',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Americo Amorim built the Amorim Group into the world\'s largest cork producer; his family remains Portugal\'s wealthiest.' }],
    rarity: 'rare',
    country: 'Portugal',
    sourceConfidence: 'verified',
  },
  'ion-tiriac': {
    slug: 'ion-tiriac',
    name: 'Ion Tiriac',
    descriptor: 'Founder — Tiriac Holdings',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Ion Tiriac founded Romania\'s first post-communist private bank and built Tiriac Holdings, becoming the first Romanian on Forbes\' billionaires list in 2007.' }],
    rarity: 'rare',
    country: 'Romania',
    sourceConfidence: 'verified',
  },
  'vladimir-potanin': {
    slug: 'vladimir-potanin',
    name: 'Vladimir Potanin',
    descriptor: 'Founder — Interros / Norilsk Nickel',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Vladimir Potanin founded the investment holding Interros and serves as president of MMC Norilsk Nickel, twice ranked Russia\'s richest person.' }],
    rarity: 'epic',
    country: 'Russia',
    sourceConfidence: 'verified',
  },
  'miroslav-miskovic': {
    slug: 'miroslav-miskovic',
    name: 'Miroslav Miskovic',
    descriptor: 'Founder — Delta Holding',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Miroslav Miskovic founded Delta M in 1991, growing it into Delta Holding, one of Serbia\'s largest conglomerates.' }],
    rarity: 'rare',
    country: 'Serbia',
    sourceConfidence: 'verified',
  },
  'ivan-jakabovic': {
    slug: 'ivan-jakabovic',
    name: 'Ivan Jakabovic',
    descriptor: 'Founder — J&T Finance Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Ivan Jakabovic co-founded J&T Finance Group in Slovakia in 1994, a major Central European financial services group.' }],
    rarity: 'rare',
    country: 'Slovakia',
    sourceConfidence: 'verified',
  },
  'igor-akrapovic': {
    slug: 'igor-akrapovic',
    name: 'Igor Akrapovic',
    descriptor: 'Founder — Akrapovic',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Igor Akrapovic founded the Slovenian company Akrapovic in 1990, a globally recognized maker of premium exhaust systems.' }],
    rarity: 'rare',
    country: 'Slovenia',
    sourceConfidence: 'verified',
  },
  'amancio-ortega': {
    slug: 'amancio-ortega',
    name: 'Amancio Ortega',
    descriptor: 'Founder — Inditex (Zara)',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Amancio Ortega founded the Inditex fashion group, including Zara, and has ranked among the world\'s richest people.' }],
    rarity: 'legendary',
    country: 'Spain',
    sourceConfidence: 'verified',
  },
  'stefan-persson': {
    slug: 'stefan-persson',
    name: 'Stefan Persson',
    descriptor: 'Investor — H&M',
    roles: ['investor'],
    timeline: [{ year: 'Present', text: 'Stefan Persson served as CEO of H&M from 1982 to 1998 and later chairman, one of Sweden\'s richest people.' }],
    rarity: 'rare',
    country: 'Sweden',
    sourceConfidence: 'verified',
  },
  'ivan-glasenberg': {
    slug: 'ivan-glasenberg',
    name: 'Ivan Glasenberg',
    descriptor: 'CEO — Glencore',
    roles: ['CEO'],
    timeline: [{ year: 'Present', text: 'Ivan Glasenberg led Glencore, the Swiss commodity trading and mining giant, as CEO from 2002 to 2021.' }],
    rarity: 'rare',
    country: 'Switzerland',
    sourceConfidence: 'verified',
  },
  'rinat-akhmetov': {
    slug: 'rinat-akhmetov',
    name: 'Rinat Akhmetov',
    descriptor: 'Founder — System Capital Management (SCM)',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Rinat Akhmetov founded System Capital Management in 2000 and is Ukraine\'s wealthiest businessman.' }],
    rarity: 'rare',
    country: 'Ukraine',
    sourceConfidence: 'verified',
  },
  'richard-branson': {
    slug: 'richard-branson',
    name: 'Richard Branson',
    descriptor: 'Founder — Virgin Group',
    roles: ['founder'],
    timeline: [{ year: 'Present', text: 'Richard Branson founded the Virgin Group in 1970, expanding it from a record label into airlines, telecoms and space tourism.' }],
    rarity: 'legendary',
    country: 'United Kingdom',
    sourceConfidence: 'verified',
  },
};

export const MOCK_COMPANIES: Record<string, CompanyProfile> = {
  apple: {
    slug: 'apple',
    name: 'Apple',
    ticker: 'AAPL',
    industry: 'Consumer technology',
    foundingYear: 1976,
    headquarters: 'United States',
    description: 'Designs consumer hardware, software and services.',
    howItMakesMoney: 'Primarily hardware sales (iPhone, Mac, wearables) plus a growing services segment.',
    timeline: [
      { year: '1976', text: 'Founded by Steve Jobs, Steve Wozniak and Ronald Wayne.' },
      { year: '1997', text: 'Near-bankruptcy; Jobs returns.' },
      { year: '2007', text: 'iPhone launches.' },
    ],
  },
  costco: {
    slug: 'costco',
    name: 'Costco',
    ticker: 'COST',
    industry: 'Retail',
    foundingYear: 1983,
    headquarters: 'United States',
    description: 'Membership-based warehouse retailer.',
    howItMakesMoney: 'Membership fees drive most profit; product margins are kept intentionally thin.',
    timeline: [{ year: '1983', text: 'First warehouse opens in Seattle.' }],
  },
  visa: {
    slug: 'visa',
    name: 'Visa',
    ticker: 'V',
    industry: 'Payments',
    foundingYear: 1958,
    headquarters: 'United States',
    description: 'Operates a global electronic payments network.',
    howItMakesMoney: 'Takes a small fee on transactions routed through its network; does not lend money directly.',
    timeline: [{ year: '2008', text: 'IPO on the NYSE.' }],
  },
  mastercard: {
    slug: 'mastercard',
    name: 'Mastercard',
    ticker: 'MA',
    industry: 'Payments',
    foundingYear: 1966,
    headquarters: 'United States',
    description: 'Operates a global electronic payments network.',
    howItMakesMoney: 'Network fees on transactions, similar to Visa.',
    timeline: [],
  },
  nvidia: {
    slug: 'nvidia',
    name: 'NVIDIA',
    ticker: 'NVDA',
    industry: 'Semiconductors',
    foundingYear: 1993,
    headquarters: 'United States',
    description: 'Designs GPUs for gaming, data centers and AI.',
    howItMakesMoney: 'Sells chips and full computing systems; increasingly for AI data centers.',
    timeline: [{ year: '2006', text: 'Launches CUDA platform.' }],
  },
};

export const MOCK_TOPICS: Record<string, TopicProfile> = {
  bonds: {
    slug: 'bonds',
    name: 'Bonds',
    category: 'Markets',
    description: 'Fixed-income securities where investors lend money for periodic interest payments.',
  },
  etfs: {
    slug: 'etfs',
    name: 'ETFs',
    category: 'Markets',
    description: 'Exchange-traded funds that bundle many securities into one tradable share.',
  },
  'market-crashes': {
    slug: 'market-crashes',
    name: 'Market Crashes',
    category: 'History',
    description: 'Sharp, sudden declines in asset prices across a market.',
  },
};
